version: '2'
services:
  www:
    image: webdevops/php-apache:alpine-3-php7
    volumes: 
      - ./www:/app
    links:
      - redis
    environment:
      - EXCLUDE_PORTS=443,9000
  haproxy:
    image: 'dockercloud/haproxy:latest'
    links:
      - www
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '8082:80'
      - '1936:1936'
  redis:
    image: redis:alpine
