version: '2'
services:
  www:
    image: php:7.0-apache
    volumes: 
      - ./www:/var/www/html
  haproxy:
    image: 'dockercloud/haproxy:latest'
    links:
      - www
    environment:
      - STATS_AUTH="admin:admin"
      - STATS_PORT=1936
      - DOCKER_TLS_VERIFY
      - DOCKER_HOST
      - DOCKER_CERT_PATH
    volumes:
      - $DOCKER_CERT_PATH:$DOCKER_CERT_PATH
    ports:
      - '80:80'
      - '1936:1936'
